server:
  port: 8081

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pethotel?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssoyeon1@3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  file:
    upload-dir: ./uploads
  thymeleaf:
    cache: false
  jackson:
    stream:
      max-nesting-depth: 2000